remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Jason Lee's presonal boolg
description: Welcome to my boolg
show_downloads: false